name 'docker_nano_host'
maintainer 'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license 'Apache 2.0'
description 'Installs/Configures docker and configures to run as a host'
long_description 'Installs/Configures docker and configures to run as a host'
version '0.1.0'
